### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by jacobhoff** [stephenap07/gif-cabinet#7]
![group er](https://cloud.githubusercontent.com/assets/11414333/7107760/03dedd08-e13e-11e4-9d6c-597ddda4321b.JPG)

**Comment by jacobhoff** [comment]
Let me know if there are any changes to the database and i'll update accordingly.

**Comment by stephenap07** [comment]
Please update this to show the one-to-many relationship between issue and comment.

**Comment by jacobhoff** [comment]
![group er](https://cloud.githubusercontent.com/assets/11414333/7297403/73406c1a-e996-11e4-9cb8-85230d12ef3b.JPG)

**Comment by jacobhoff** [comment]
Updated Group ER Diagram
